In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.4-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\aaago\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\aaago\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.4-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------- ----------------- 5.5/9.7 MB 37.3 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 32.4 MB/s  0:00:00
Downloading numpy-2.5.0-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ----------------------------------- ---- 11.0/12.4 MB 53.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 42.6 MB/s  0:00:00
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.0 pandas-3.0.4 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

In [ ]:
xor_input = [
    [0,0,0],
    [0,1,1],
    [1,0,1],
    [1,1,0]
]
print(xor_input)

[[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0]]

In [6]:
xor_df = pd.DataFrame(xor_input)
xor_df

   0  1  2
0  0  0  0
1  0  1  1
2  1  0  1
3  1  1  0

In [7]:
# 데이터 구성(문제)
xor_data = xor_df.loc[:,[0,1]]
xor_data

   0  1
0  0  0
1  0  1
2  1  0
3  1  1

In [8]:
# 정답
xor_target = xor_df.loc[:,2]
xor_target

0    0
1    1
2    1
3    0
Name: 2, dtype: int64

In [9]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\aaago\miniconda3\Lib\site-packages (from scikit-learn) (2.5.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   -------- ------------------------------- 7.9/36.6 MB 40.0 MB/s eta 0:00:01
   ------------------ --------------------- 17.3/36.6 MB 43.2 MB/s eta 0:00:01
   ------------------------------ --------- 28.0/36.6 MB 45.2 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 38.9 MB/s  0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0

In [10]:
# 데이터 학습과 예측하기
from sklearn import svm, metrics

In [11]:
# 모델 만들기
clf = svm.SVC()

In [31]:
# 학습시키기
clf.fit(xor_data, xor_target)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2950: illegal multibyte sequence

UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2950: illegal multibyte sequence

SVC()

In [12]:
import os
os.environ["PYTHONUTF8"] = "1"
os.environ["PYTHONIOENCODING"] = "utf-8"

In [16]:
# 평가하기
pred = clf.predict(xor_data)
pred

NameError: name 'clf' is not defined

In [ ]:
# 정답률 구하기
metrics.accuracy_score(xor_target, pred)

In [ ]:
# predict를 구하지 않고 정답률 구하기
clf.score(xor_data, xor_target)

### 붓꽃의 품종 분류하기

In [ ]:
iris = pd.read_csv('../Data/iris.csv').head()
iris

In [ ]:
iris.tail()