## 특성(Feature)공학과 규제(Regularization : 정형화, 일반화, 규제)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/fish.csv")
df.head()

   length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94

In [3]:
fish_full = df.to_numpy()
fish_full[:5]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94]])

In [4]:
df = pd.read_csv("../Data/fish_weight.csv")
df.head()

   weight
0     5.9
1    32.0
2    40.0
3    51.5
4    70.0

In [5]:
fish_weight = df.to_numpy()
fish_weight[:5]

array([[ 5.9],
       [32. ],
       [40. ],
       [51.5],
       [70. ]])

In [6]:
# Train 과 Test
from sklearn.model_selection import train_test_split

In [7]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        fish_full,
        fish_weight,
        random_state=42
    )

## sklearn 으로 다중회귀 분석 하기

---
#### 다항 특성 만들기 실습

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
# 다항 특성 만들기
poly = PolynomialFeatures()
poly.fit([[2, 3]])
poly.transform([[2, 3]])

array([[1., 2., 3., 4., 6., 9.]])

In [10]:
poly = PolynomialFeatures(include_bias=False) # degree = 2
poly.fit([[2, 3]])
poly.transform([[2, 3]])

array([[2., 3., 4., 6., 9.]])

In [11]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

---
#### 다항 특성 만들기

In [12]:
train_input.shape

(42, 3)

In [13]:
# train_input 을 다항 특성 만들기
poly = PolynomialFeatures(include_bias=False) # degree = 2
train_poly = poly.fit_transform(train_input)

In [14]:
train_poly.shape

(42, 9)

In [15]:
# 컬럼 정보 확인
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [16]:
train_poly[:5]

array([[  19.6   ,    5.14  ,    3.04  ,  384.16  ,  100.744 ,   59.584 ,
          26.4196,   15.6256,    9.2416],
       [  22.    ,    5.88  ,    3.52  ,  484.    ,  129.36  ,   77.44  ,
          34.5744,   20.6976,   12.3904],
       [  18.7   ,    5.2   ,    3.12  ,  349.69  ,   97.24  ,   58.344 ,
          27.04  ,   16.224 ,    9.7344],
       [  17.4   ,    4.59  ,    2.94  ,  302.76  ,   79.866 ,   51.156 ,
          21.0681,   13.4946,    8.6436],
       [  36.    ,   10.61  ,    6.74  , 1296.    ,  381.96  ,  242.64  ,
         112.5721,   71.5114,   45.4276]])

In [17]:
# test_input 도 다항특성 만들기
test_poly = poly.transform(test_input)
test_poly.shape

(14, 9)

#### 다중 회귀 모델 훈련하기

In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [19]:
lr.fit(train_input, train_target)
print("Train :", lr.score(train_input, train_target))
print("Test :", lr.score(test_input, test_target))

Train : 0.9559326821885706
Test : 0.8796419177546366

In [20]:
lr.fit(train_poly, train_target)
print("Train :", lr.score(train_poly, train_target))
print("Test :", lr.score(test_poly, test_target))

Train : 0.9903183436982124
Test : 0.9714559911594145

---
#### 더 많은 특성 만들기

In [29]:
poly = PolynomialFeatures(include_bias=False, degree=5)
poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)

In [30]:
train_poly.shape

(42, 55)

In [31]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2', 'x0^3', 'x0^2 x1', 'x0^2 x2', 'x0 x1^2', 'x0 x1 x2',
       'x0 x2^2', 'x1^3', 'x1^2 x2', 'x1 x2^2', 'x2^3', 'x0^4', 'x0^3 x1',
       'x0^3 x2', 'x0^2 x1^2', 'x0^2 x1 x2', 'x0^2 x2^2', 'x0 x1^3',
       'x0 x1^2 x2', 'x0 x1 x2^2', 'x0 x2^3', 'x1^4', 'x1^3 x2',
       'x1^2 x2^2', 'x1 x2^3', 'x2^4', 'x0^5', 'x0^4 x1', 'x0^4 x2',
       'x0^3 x1^2', 'x0^3 x1 x2', 'x0^3 x2^2', 'x0^2 x1^3',
       'x0^2 x1^2 x2', 'x0^2 x1 x2^2', 'x0^2 x2^3', 'x0 x1^4',
       'x0 x1^3 x2', 'x0 x1^2 x2^2', 'x0 x1 x2^3', 'x0 x2^4', 'x1^5',
       'x1^4 x2', 'x1^3 x2^2', 'x1^2 x2^3', 'x1 x2^4', 'x2^5'],
      dtype=object)

In [32]:
lr.fit(train_poly, train_target)
print("Train :", lr.score(train_poly, train_target))
print("Test :", lr.score(test_poly, test_target))

Train : 0.9953852031717493
Test : 0.9780184172675167

> -> 원래 과대적합에 의해 Test 값이 매우 크게 범위에서 벗어나야 함(음수값). 이유는 모르겠지만 안정적인 수로 출력됨

#### 규제
모델이 과적합되게 학습하지 않고 일반성을 가질 수 있도록 규제(정규화) 하는 것

In [34]:
# 규제 전에 표준화
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_poly)

train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

#### Ridge(L2규제) 규제
: 가중치의 제곱으로 규제하는 방법

In [35]:
from sklearn.linear_model import Ridge

In [37]:
ridge = Ridge()
ridge.fit(train_scaled, train_target)
print("Train :", ridge.score(train_scaled, train_target))
print("Test :", ridge.score(test_scaled, test_target))

Train : 0.9896101671037343
Test : 0.9790693977615379

#### 적절한 규제 강도(Hyper Parameter) 찾기

In [39]:
train_score = []
test_score = []

alpha_list = [0.001, 0.01, 0.1, 1, 10, 100] # 임의로 정한다.

for alpha in alpha_list:
    ridge = Ridge(alpha=alpha)
    ridge.fit(train_scaled, train_target)
    train_score.append(ridge.score(train_scaled, train_target))
    test_score.append(ridge.score(test_scaled, test_target))

In [43]:
pd.DataFrame(
    {
        'Train' : train_score,
        'Test' : test_score
    }
)

      Train      Test
0  0.993046  0.956939
1  0.991781  0.980019
2  0.990382  0.982798
3  0.989610  0.979069
4  0.988728  0.972533
5  0.984184  0.962704

> 2 번째 데이터 즉, alpha 값이 0.1 일 때 가장 좋은 학습 효율

In [44]:
ridge = Ridge(alpha=0.1)
ridge.fit(train_scaled, train_target)
print("Train :", ridge.score(train_scaled, train_target))
print("Test :", ridge.score(test_scaled, test_target))

Train : 0.9903815817570368
Test : 0.9827976465386983

특성공학은 모델 학습 초반 정확도가 너무 안좋을 때 사용할 것